datasource:
  port: 5432
  schema: public

context:
  initializer:
    classes: dev.citc.samples.loom.boot.Application

spring:
  datasource:
    password: ${datasource.password}
    hikari:
      initialization-fail-timeout: '20000'
      maximum-pool-size: '40'
      schema: ${datasource.schema}
    url: jdbc:postgresql://${datasource.host}:${datasource.port}/${datasource.database}
    username: ${datasource.username}
  web:
    resources:
      add-mappings: 'false'
server:
  jetty:
    # (optional) no need for many platform threads because requests handled by virtual threads
    threads:
      min: 0
