datasource:
  port: 5432
  schema: public

context:
  initializer:
    classes: dev.citc.samples.loom.boot.Application

spring:
  datasource:
    password: ${datasource.password}
    hikari:
      initialization-fail-timeout: '20000'
      maximum-pool-size: '80'
      schema: ${datasource.schema}
    url: jdbc:postgresql://${datasource.host}:${datasource.port}/${datasource.database}
    username: ${datasource.username}
  web:
    resources:
      add-mappings: 'false'
server:
  jetty:
    # for default settings 8/200 Jetty allocates 200 threads and not use it... So shrink it to minimum
    threads:
      max: 8
      min: 8
