---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - populate-test-data.job.yaml
configMapGenerator:
  - name: test-data-sql
    files:
      - script.sql=test_data.sql
secretGenerator:
  - name: postgresql-dev-db-secret
    literals:
      - host=postgresql-dev-db
      - port=5432
      - database=devdb
      - username=devdb_owner
      - password=password
      - type=postgres
