apiVersion: v1
kind: Service
metadata:
  name: postgresql-dev-db
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgresql-dev-db
---
kind: PriorityClass
apiVersion: scheduling.k8s.io/v1
metadata:
  name: postgresql-priority-class
value: 100
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-dev-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-dev-db
  labels:
    app.kubernetes.io/name: postgresql-dev-db
spec:
  serviceName: postgresql-dev-db
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql-dev-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql-dev-db
    spec:
      priorityClassName: postgresql-priority-class
      containers:
        - name: postgres
          image: postgres:15.2
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql-dev-db-secret
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-dev-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-dev-db-secret
                  key: password
          ports:
            - containerPort: 5432
              name: postgres
          resources:
            requests:
              cpu: 100m
              memory: 500M
            limits:
              cpu: '4'
              memory: 1G
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql
            - name: initial-data
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: postgresql-dev-db-pvc
        - name: initial-data
          configMap:
            name: postgresql-dev-db-initial-data
            optional: true
