---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-loom-jdbc
  labels:
    app.kubernetes.io/name: boot-loom-jdbc
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: samples
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: boot-loom-jdbc
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: samples
  template:
    metadata:
      labels:
        app.kubernetes.io/name: boot-loom-jdbc
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: samples
    spec:
      serviceAccountName: boot-loom-jdbc
      containers:
        - name: boot-loom-jdbc
          image: ghcr.io/cit-consulting/boot-loom-jdbc
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: optional:configtree:/config.d/*/
          resources:
            requests:
              cpu: 100m
              memory: "1Gi"
            limits:
              cpu: "4"
              memory: "1Gi"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 120
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8181
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8181
            initialDelaySeconds: 10
            periodSeconds: 30
          securityContext:
            readOnlyRootFilesystem: true
          # reads: application.yaml
          volumeMounts:
            - name: app-config
              mountPath: /config
              readOnly: true
            - name: temp
              mountPath: /tmp
      volumes:
        - name: app-config
          secret:
            secretName: boot-loom-jdbc-config
            optional: true
        - name: temp
          emptyDir:
            sizeLimit: 10M
