---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boot-loom-jdbc
  labels:
    app.kubernetes.io/name: boot-loom-jdbc
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: samples
