apiVersion: v1
kind: Service
metadata:
  name: boot-loom-jdbc
  labels:
    app.kubernetes.io/name: boot-loom-jdbc
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: samples
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8181"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: boot-loom-jdbc
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: samples
  ports:
    - name: http
      port: 8080
      targetPort: http
